//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLySieuThi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2015_Edeka_Patschull_Darmstadt_GOLZ3009 {
            get {
                object obj = ResourceManager.GetObject("2015_Edeka_Patschull_Darmstadt_GOLZ3009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3c4d8cea83023c9cf31fb083e49d4ec0 {
            get {
                object obj = ResourceManager.GetObject("3c4d8cea83023c9cf31fb083e49d4ec0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frewville_Foodland_10215400 {
            get {
                object obj = ResourceManager.GetObject("Frewville-Foodland-10215400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap korea_supermarket_PML6544 {
            get {
                object obj = ResourceManager.GetObject("korea_supermarket_PML6544", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimal_Wallpaper_HD_for_Phone_052 {
            get {
                object obj = ResourceManager.GetObject("Minimal-Wallpaper-HD-for-Phone-052", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noun_profile_956157 {
            get {
                object obj = ResourceManager.GetObject("noun_profile_956157", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCC_Edmonds_DSC_7333_HDR {
            get {
                object obj = ResourceManager.GetObject("PCC-Edmonds-DSC_7333-HDR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PCC_Edmonds_DSC_7333_HDR1 {
            get {
                object obj = ResourceManager.GetObject("PCC-Edmonds-DSC_7333-HDR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap R {
            get {
                object obj = ResourceManager.GetObject("R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap R__1_ {
            get {
                object obj = ResourceManager.GetObject("R (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap R__1_1 {
            get {
                object obj = ResourceManager.GetObject("R (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wp3152222 {
            get {
                object obj = ResourceManager.GetObject("wp3152222", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wp3152292 {
            get {
                object obj = ResourceManager.GetObject("wp3152292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wp3152338 {
            get {
                object obj = ResourceManager.GetObject("wp3152338", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749036721571_507bd97faa53540115fd48d19e368710 {
            get {
                object obj = ResourceManager.GetObject("z3749036721571_507bd97faa53540115fd48d19e368710", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749036721571_507bd97faa53540115fd48d19e3687101 {
            get {
                object obj = ResourceManager.GetObject("z3749036721571_507bd97faa53540115fd48d19e3687101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749276896437_b1af42559f50fbffcc2ecf9b6fcb38e0 {
            get {
                object obj = ResourceManager.GetObject("z3749276896437_b1af42559f50fbffcc2ecf9b6fcb38e0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749334893128_f38b6f7ca47f27381e0efc241dfa1670 {
            get {
                object obj = ResourceManager.GetObject("z3749334893128_f38b6f7ca47f27381e0efc241dfa1670", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749334893128_f38b6f7ca47f27381e0efc241dfa16701 {
            get {
                object obj = ResourceManager.GetObject("z3749334893128_f38b6f7ca47f27381e0efc241dfa16701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749336767361_caacf940de35e6e4e5d46aafd8b3da08 {
            get {
                object obj = ResourceManager.GetObject("z3749336767361_caacf940de35e6e4e5d46aafd8b3da08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749336767361_caacf940de35e6e4e5d46aafd8b3da081 {
            get {
                object obj = ResourceManager.GetObject("z3749336767361_caacf940de35e6e4e5d46aafd8b3da081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749336767361_caacf940de35e6e4e5d46aafd8b3da082 {
            get {
                object obj = ResourceManager.GetObject("z3749336767361_caacf940de35e6e4e5d46aafd8b3da082", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749338716857_314c8e61e6df298fc90ddb81ac525b22 {
            get {
                object obj = ResourceManager.GetObject("z3749338716857_314c8e61e6df298fc90ddb81ac525b22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749339594072_840ea59b469f9990c4eee707b8298f7a {
            get {
                object obj = ResourceManager.GetObject("z3749339594072_840ea59b469f9990c4eee707b8298f7a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749342510936_a8f58c27b71c08a76073fe7771693ccf {
            get {
                object obj = ResourceManager.GetObject("z3749342510936_a8f58c27b71c08a76073fe7771693ccf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749345061403_c576d57c9fbb28e6e3672f130c83bd62 {
            get {
                object obj = ResourceManager.GetObject("z3749345061403_c576d57c9fbb28e6e3672f130c83bd62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749345061403_c576d57c9fbb28e6e3672f130c83bd621 {
            get {
                object obj = ResourceManager.GetObject("z3749345061403_c576d57c9fbb28e6e3672f130c83bd621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749348317778_b50760d5dda85b40816da325ae205467 {
            get {
                object obj = ResourceManager.GetObject("z3749348317778_b50760d5dda85b40816da325ae205467", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749350732204_f4da31561bf72e0f1dd9fc0cb104c0d4 {
            get {
                object obj = ResourceManager.GetObject("z3749350732204_f4da31561bf72e0f1dd9fc0cb104c0d4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3749358122862_8eff713b154f89576630d0a896812ed3 {
            get {
                object obj = ResourceManager.GetObject("z3749358122862_8eff713b154f89576630d0a896812ed3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3756782194267_9d7c53cc8c221adab5ecea886281c57a {
            get {
                object obj = ResourceManager.GetObject("z3756782194267_9d7c53cc8c221adab5ecea886281c57a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z3770207997100_8b6d4f72302f80f0b473b467ad810908 {
            get {
                object obj = ResourceManager.GetObject("z3770207997100_8b6d4f72302f80f0b473b467ad810908", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
